## Fiddling about with spectra

In [1]:
# imports
from specdb.specdb import SpecDB,IgmSpec
import astropy.units as u
igmsp = IgmSpec(verbose=False)
spec, meta = igmsp.spec_from_coord('00:40:54.7-09:15:27',verbose=False,isurvey=['SDSS_DR7'])
igmsp.qcat.surveys

Using /Users/lwymarie/Desktop/IGMspec_DB_v02.hdf5 for the catalog file
Using /Users/lwymarie/Desktop/IGMspec_DB_v02.hdf5 for the DB file
Available surveys: [u'BOSS_DR12', u'HSTQSO', u'SDSS_DR7', u'KODIAQ_DR1', u'MUSoDLA', u'HD-LLS_DR1', u'2QZ', u'ESI_DLA', u'HDLA100', u'GGG', u'COS-Halos', u'HST_z2', u'COS-Dwarfs', u'XQ-100']
Database is igmspec
Created on 2016-Oct-25


/Users/lwymarie/python/linetools/linetools/spectra/xspectrum1d.py:297: UserWarning: No unit given to wavelength, assuming Angstroms.
  warnings.warn("No unit given to wavelength, assuming Angstroms.")


[u'2QZ',
 u'BOSS_DR12',
 u'COS-Dwarfs',
 u'COS-Halos',
 u'ESI_DLA',
 u'GGG',
 u'HD-LLS_DR1',
 u'HDLA100',
 u'HSTQSO',
 u'HST_z2',
 u'KODIAQ_DR1',
 u'MUSoDLA',
 u'SDSS_DR7',
 u'XQ-100']

## Load QPQ

In [2]:
qpq_fil = '/Users/lwymarie/Desktop/qpq_optical.hdf5'

In [3]:
qpqsp = SpecDB(db_file=qpq_fil,idkey='PRIV_ID')

Using /Users/lwymarie/Desktop/qpq_optical.hdf5 for the catalog file
Using /Users/lwymarie/Desktop/qpq_optical.hdf5 for the DB file
Available surveys: [u'GMOS', u'MODS', u'HIRES', u'MMT', u'XSHOOTER', u'MIKE', u'BOSS', u'MAGE', u'LRIS', u'SDSS', u'ESI']
Database is QPQ
Created on 2016-Oct-11


In [30]:
qpqsp.cat['RA'][12*36+4-1],qpqsp.cat['DEC'][12*36+4-1]

(180.12145833333332, 1.4961944444444446)

In [3]:
from astropy import units as u
from astropy.coordinates import SkyCoord
c = SkyCoord(ra=150.696425115*u.degree, dec=0.348057780352*u.degree, frame='icrs')
c.to_string('hmsdms')

u'10h02m47.142s +00d20m53.008s'

In [76]:
qpqsp.cat.keys()

['sig_zem',
 'flag_zem',
 'flag_survey',
 'zem',
 'RA',
 'DEC',
 'IGM_ID',
 'STYPE',
 'PRIV_ID']

In [6]:
import astropy.units as u
(specs, metas) = qpqsp.spec_from_coord((227.053328443*u.deg,36.5917417532*u.deg),private=True)
import numpy as np
import matplotlib.pyplot as plt
metas

Your search yielded 8 match[es]


[<Table length=8>
 sig_zem flag_zem flag_survey      zem      ... GRATING SURVEY_ID VERSION
 float64   str9      int64       float64    ...   str4     str5     str7 
 ------- -------- ----------- ------------- ... ------- --------- -------
     0.0      QPQ           1         2.105 ...    BOTH     DUMMY  v5_5_0
     0.0 BOSS_PCA           1 2.09800004959 ...    BOTH     DUMMY  v5_5_0
     0.0      QPQ           1         2.105 ...    BOTH     DUMMY  v5_5_0
     0.0 BOSS_PCA           1 2.09800004959 ...    BOTH     DUMMY  v5_5_0
     0.0      QPQ           1         2.105 ...    BOTH     DUMMY  v5_5_0
     0.0 BOSS_PCA           1 2.09800004959 ...    BOTH     DUMMY  v5_5_0
     0.0      QPQ           1         2.105 ...    BOTH     DUMMY  v5_5_0
     0.0 BOSS_PCA           1 2.09800004959 ...    BOTH     DUMMY  v5_5_0,
 <Table length=1>
 sig_zem flag_zem flag_survey   zem   ... INSTR TELESCOPE SURVEY_ID
 float64   str9      int64    float64 ...  str5    str6      str5  
 ------- ----

In [ ]:
specs[1].plot()

In [42]:
[None,None] is None

False

In [ ]:
%matplotlib inline
spec[-1].normalize(spec[-1].co)
spec[-1].normalized_spec().plot()

In [139]:
spec[0].data['wave'][0].data[0]

3993.5324129177138

In [144]:
for ii,cc in enumerate(conti):
    if (conti[ii] != conti[ii+1]):
        print(ii+1)
        break


711


In [146]:
meta[0]['SPEC_FILE']

<Column name='SPEC_FILE' dtype='str78' length=1>
/u/xavier/Dropbox//QSOPairs/data/ESI_redux/./SDSSJ022519.50+004823.7_F.fits.gz

In [17]:
igmsp = SpecDB(db_file='/Users/lwymarie/Desktop/IGMspec_DB_v02.hdf5')
spec2, meta2 = igmsp.spec_from_coord((10.818782*u.deg,0.179202*u.deg))
meta2

Using /Users/lwymarie/Desktop/IGMspec_DB_v02.hdf5 for the catalog file
Using /Users/lwymarie/Desktop/IGMspec_DB_v02.hdf5 for the DB file
Available surveys: [u'BOSS_DR12', u'HSTQSO', u'SDSS_DR7', u'KODIAQ_DR1', u'MUSoDLA', u'HD-LLS_DR1', u'2QZ', u'ESI_DLA', u'HDLA100', u'GGG', u'COS-Halos', u'HST_z2', u'COS-Dwarfs', u'XQ-100']
Database is igmspec
Created on 2016-Oct-25
Your search yielded 1 match[es]


[<Table length=1>
       SDSSJ            RA      DEC    ... GRATING TELESCOPE  flag_zem
       str31         float64  float64  ...   str4    str10     str10  
 ------------------ --------- -------- ... ------- ---------- --------
 004316.50+001045.1 10.818782 0.179202 ...    BOTH SDSS 2.5-M  SDSS-HW]

In [19]:
spec2[1].plot()

IndexError: list index out of range

In [4]:
from astropy import units as u
spec3, meta3 = qpqsp.spec_from_coord('142054.42+160333.3',private=True)
meta3[0]

Your search yielded 1 match[es]


<Table length=1>
sig_zem flag_zem flag_survey   zem   ... INSTR TELESCOPE SURVEY_ID
float64   str9      int64    float64 ...  str5    str6      str5  
------- -------- ----------- ------- ... ----- --------- ---------
    0.0      QPQ           1   2.012 ... LRISb    Keck-I     DUMMY

In [134]:
spec3[0].plot()

In [ ]:
spec3[2].sig

In [ ]:
import numpy as np
len(spec3[2].flux)

In [ ]:
meta3[2]

In [ ]:
len(spec3[0:-1][0].flux)

In [ ]:
spec3[0].flux

In [ ]:
spec3[0].sig

In [14]:
spec_file = '/Marie_X/QPQ9/Continuua/XSHOOTER/SDSSJ091338.97-010704.6_F_c.fits'

In [ ]:
'J0913' in spec_file and 'XSHOOTER' in spec_file

In [25]:
spec4, meta4 = igmsp.spec_from_coord('074853.65+222525.2')

Your search yielded 0 match[es]


In [ ]:
meta3[['INSTR']

In [ ]:
'XSHOOTER' in meta3[2]['INSTR'][0]

In [ ]:
type(meta3)

In [ ]:
for meta in meta3:
    print('XSHOOTER' in meta['INSTR'][0])

In [ ]:
spec3[0]

In [ ]:
str1 = 'MagE'

In [ ]:
dir(str1)

In [ ]:
str1.capitalize

In [ ]:
str1.upper()

In [29]:
import matplotlib.pyplot as plt
import numpy as np
plt.plot(np.array([1,2,3]),np.array([1,2,3]))
plt.ylim(-2,2)
plt.show()

In [27]:
mpl.plot?

In [89]:
alist = [1,2,3]

In [90]:
alist[-1],alist[-2],alist[-3]

(3, 2, 1)

In [15]:
import numpy as np
wave = np.outer(np.ones(3), np.arange(100))

In [16]:
wave

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
         22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
         33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
         44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
         55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
         66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
         77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
         88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
         99.],
       [  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
         22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
         33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
         44.,  45.,  46

[0]

In [55]:
nplt = 32 
pages = nplt//15 + ((nplt % 15) > 0)
for ipage in range(pages):
    print(ipage)
range(pages)[0:3]

0
1
2


[0, 1, 2]

In [50]:
outfil = 'plt_qpq9_zNIR_{:d}_page{:d}.pdf'.format(1,2+1)
outfil

'plt_qpq9_zNIR_1_page3.pdf'

In [16]:
np.log(2.7)

0.99325177301028345

In [17]:
np.sqrt(4)

2.0

In [20]:
tau = np.array([1,2,3])
tau**2

array([1, 4, 9])

In [21]:
help(np.sum)

Help on function sum in module numpy.core.fromnumeric:

sum(a, axis=None, dtype=None, out=None, keepdims=False)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In that case, if `a` is signe

In [24]:
cumtau = np.cumsum(np.array([1,2,3]))

In [26]:
np.where(cumtau > 1)

(array([1, 2]),)

In [22]:
wavelength = np.array([1,2,3,4,5])
np.where((wavelength > 1) & (wavelength < 5))

(array([1, 2, 3]),)

In [82]:
from specdb.specdb import IgmSpec
igmsp = IgmSpec()
from astropy.cosmology import FlatLambdaCDM
cosmo = FlatLambdaCDM(H0=70, Om0=0.26)
kpc_amin = cosmo.kpc_proper_per_arcmin(1.7)
print(0.57*u.amin*kpc_amin)

Using /Users/lwymarie/Desktop/IGMspec_DB_v02.hdf5 for the catalog file
Using /Users/lwymarie/Desktop/IGMspec_DB_v02.hdf5 for the DB file
Available surveys: [u'BOSS_DR12', u'HSTQSO', u'SDSS_DR7', u'KODIAQ_DR1', u'HD-LLS_DR1', u'2QZ', u'ESI_DLA', u'HDLA100', u'GGG', u'COS-Halos', u'HST_z2', u'COS-Dwarfs', u'XQ-100']
Database is igmspec
Created on 2016-Oct-10
299.354234775 amin kpc / arcmin


In [104]:
ID_fg, ID_bg = igmsp.pairs(0.57*u.arcmin, 3000.*u.km/u.s)
#igmsp.show_cat(ID_fg)
ID_fg

<Column name='IGM_ID' dtype='int64' length=1829>
    96
   293
   434
   851
  1006
  1243
  1638
  2490
  2748
  2830
  2872
  2940
   ...
401307
401332
401360
401378
401449
402197
402479
402704
402775
403017
403075
403083

In [77]:
qpqsp.cat['IGM_ID']

<Column name='IGM_ID' dtype='int64' length=8454>
 23591
 25868
 25900
 26939
 32382
 36445
 48329
 56495
 59502
118007
143820
145634
   ...
245458
247069
372101
  8844
220830
 -9999
 -9999
 -9999
 -9999
285367
285370
291728

In [86]:
counter = 0
for ii in ID_bg:
    if ii not in qpqsp.cat['IGM_ID']:
        print(ii)
        counter += 1
print(counter)

105
291
859
1009
1232
1637
2499
2754
2824
2876
2942
3280
3506
3982
302658
5296
5335
5736
6112
6369
6434
6595
6823
6887
7086
7124
7729
303082
9379
9719
10059
10153
10352
10715
11429
11440
11889
11975
12158
12351
13030
13130
13141
13744
14790
14823
15040
15621
15859
16081
16267
17003
17088
17434
17722
18059
18090
18110
18138
18260
18407
19106
304556
20605
20691
21648
22139
305046
22974
24152
24414
24447
24483
25545
25549
26020
26070
26679
26934
27010
27050
27478
27598
29209
29561
306228
31347
306406
306465
32623
33100
33604
33859
33879
306873
34014
34296
34364
34578
35044
35082
35123
35190
35299
35387
35415
35621
307091
35882
35919
35923
35979
36116
36224
36221
36284
36320
36352
36422
36451
36467
36580
36638
36693
36696
36700
36742
36915
36955
37056
37138
37320
37569
37600
37924
38107
38187
38476
38614
38668
38934
38980
39051
39180
39237
39363
39382
39438
39570
39643
41284
310245
43131
310899
44369
311581
45468
45668
46914
312346
47364
47677
312561
48063
48180
48241
48490
49134
49525
495

In [87]:
qpqsp.show_cat(438)

IGM_ID    RA      DEC     zem   flag_survey sig_zem flag_zem STYPE PRIV_ID
------ -------- -------- ------ ----------- ------- -------- ----- -------
   438   0.3685   8.6760  3.728           1   0.000 BOSS_PCA   QSO    5431
   438   0.3685   8.6760  3.728           1   0.000 BOSS_PCA   QSO    7738
----------
Survey key:
    BOSS: 1
    ESI: 2
    GMOS: 4
    HIRES: 16
    LRIS: 128
    MAGE: 256
    MIKE: 512
    MMT: 1024
    MODS: 2048
    SDSS: 32768
    XSHOOTER: 131072


In [91]:
qpqsp.cat[5431]

<Row index=5431>
sig_zem flag_zem flag_survey   zem      RA      DEC    IGM_ID STYPE PRIV_ID
float64   str9      int64    float64 float64  float64  int64   str3  int64 
------- -------- ----------- ------- -------- -------- ------ ----- -------
  0.000 BOSS_PCA           1   3.728   0.3685   8.6760    438   QSO    5431

In [203]:
specs, metas = qpqsp.spec_from_coord((120.20306832*u.deg,35.7086976546*u.deg),private=True)
metas

Your search yielded 1 match[es]
Staged 0 spectra totalling 0 Gb
No spectra matching in survey BOSS
Staged 0 spectra totalling 0 Gb
No spectra matching in survey ESI
Staged 0 spectra totalling 0 Gb
No spectra matching in survey GMOS
Staged 0 spectra totalling 0 Gb
No spectra matching in survey HIRES
Staged 1 spectra totalling 8.4e-05 Gb
Loaded spectra
Staged 0 spectra totalling 0 Gb
No spectra matching in survey MAGE
Staged 0 spectra totalling 0 Gb
No spectra matching in survey MIKE
Staged 0 spectra totalling 0 Gb
No spectra matching in survey MMT
Staged 0 spectra totalling 0 Gb
No spectra matching in survey MODS
Staged 0 spectra totalling 0 Gb
No spectra matching in survey SDSS
Staged 0 spectra totalling 0 Gb
No spectra matching in survey XSHOOTER


[<Table length=1>
 sig_zem flag_zem flag_survey   zem   ... INSTR TELESCOPE SURVEY_ID
 float64   str9      int64    float64 ...  str5    str6      str5  
 ------- -------- ----------- ------- ... ----- --------- ---------
     0.0      QPQ           1   2.064 ... LRISb    Keck-I     DUMMY]

In [100]:
specs, metas = igmsp.spec_from_coord((0.3685,8.6760))
metas[0]

Your search yielded 1 match[es]
Staged 0 spectra totalling 0 Gb
No spectra matching in survey 2QZ
Staged 1 spectra totalling 9.3e-05 Gb
Loaded spectra
Staged 0 spectra totalling 0 Gb
No spectra matching in survey COS-Dwarfs
Staged 0 spectra totalling 0 Gb
No spectra matching in survey COS-Halos
Staged 0 spectra totalling 0 Gb
No spectra matching in survey ESI_DLA
Staged 0 spectra totalling 0 Gb
No spectra matching in survey GGG
Staged 0 spectra totalling 0 Gb
No spectra matching in survey HD-LLS_DR1
Staged 0 spectra totalling 0 Gb
No spectra matching in survey HDLA100
Staged 0 spectra totalling 0 Gb
No spectra matching in survey HSTQSO
Staged 0 spectra totalling 0 Gb
No spectra matching in survey HST_z2
Staged 0 spectra totalling 0 Gb
No spectra matching in survey KODIAQ_DR1
Staged 0 spectra totalling 0 Gb
No spectra matching in survey SDSS_DR7
Staged 0 spectra totalling 0 Gb
No spectra matching in survey XQ-100


<Table length=1>
    SDSS_NAME            RA            DEC      ... INSTR GRATING TELESCOPE 
      str18           float64        float64    ...  str4   str4    str10   
------------------ -------------- ------------- ... ----- ------- ----------
000128.44+084033.5 0.368506876232 8.67598577342 ...  BOSS    BOTH SDSS 2.5-M

In [101]:
for ii in ID_fg:
    if ii in ID_bg:
        print('repeated',ii)

('repeated', 256807)
('repeated', 343678)


In [109]:
from astropy.io import fits
data = fits.open('../Analysis/Stacks/QPQ9_zIRMgII_1334.fits')

In [130]:
dat = np.transpose([data[0].data,data[1].data,np.zeros_like(data[1].data)])

In [131]:
from astropy.io import ascii
import sys
ascii.write(dat, sys.stdout, delimiter=' ',format='no_header')

0.9700400233268738 1321.2438935755008 0.0
0.9806720018386841 1321.6847293082908 0.0
0.9740078449249268 1322.1257092802687 0.0
0.9691532850265503 1322.566833635886 0.0
0.9640882611274719 1323.0081025197353 0.0
0.9731051921844482 1323.4495160765514 0.0
0.9689950942993164 1323.891074451212 0.0
0.9593449831008911 1324.3327777887373 0.0
0.9298703670501709 1324.7746262342898 0.0
0.9671471118927002 1325.216619933176 0.0
0.9774489402770996 1325.6587590308447 0.0
0.9605249166488647 1326.1010436728889 0.0
0.9561501741409302 1326.5434740050455 0.0
0.9597588777542114 1326.986050173195 0.0
0.9510238170623779 1327.4287723233629 0.0
0.9826961159706116 1327.8716406017184 0.0
0.9722848534584045 1328.314655154576 0.0
0.9555654525756836 1328.7578161283952 0.0
0.9776575565338135 1329.2011236697806 0.0
0.9879497289657593 1329.644577925482 0.0
0.9552170634269714 1330.088179042396 0.0
0.9480270147323608 1330.5319271675637 0.0
0.9264969229698181 1330.9758224481739 0.0
0.933535635471344 1331.419865031561 0.0
0

In [126]:
f = open('data_new.txt', 'wb')
help(f.write)

Help on built-in function write:

write(...)
    write(str) -> None.  Write string str to file.
    
    Note that due to buffering, flush() or close() may be needed before
    the file on disk reflects the data written.



In [138]:
import warnings 
warnings.warn('Using a sub-grid wavelength array because the input array is too coarse.')

/Users/lwymarie/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: UserWarning: Using a sub-grid wavelength array because the input array is too coarse.
  from ipykernel import kernelapp as app


In [2]:
from astropy.table import Column
from xastropy.xutils import fits as xxf
import imp
import numpy as np
from astropy import units as u
from astropy.coordinates import SkyCoord
enigma_path = imp.find_module('enigma')[1]
liam = xxf.bintab_to_table(enigma_path+'/data/redshifts/masterlist_liam.fits')
c_liam = SkyCoord(liam['RAJ2000'], liam['DEJ2000'], frame='icrs')

x.fits.bintab_to_table: Reading /Users/lwymarie/python/enigma/enigma/data/redshifts/masterlist_liam.fits


In [46]:
new_qpq9 = xxf.bintab_to_table('/Users/lwymarie/Dropbox/Marie_Enrico/papers/QPQ9/Analysis/qpq9_final.fits')
c_QPQ9 = SkyCoord(new_qpq9['FG_RA']*u.deg,new_qpq9['FG_DEC']*u.deg,frame='icrs')
c_QPQ9.to_string('hmsdms')

x.fits.bintab_to_table: Reading /Users/lwymarie/Dropbox/Marie_Enrico/papers/QPQ9/Analysis/qpq9_final.fits


[u'00h34m23.0635s -10d50m02.0012s',
 u'00h57m17.3646s -00d01m13.3303s',
 u'01h49m17.1049s -00d21m41.6461s',
 u'02h25m17.6801s +00d48m21.966s',
 u'02h30m18.2659s -03d33m19.4168s',
 u'03h41m38.1578s +00d00m02.9332s',
 u'04h09m55.872s -04d11m26.9365s',
 u'07h52m59.8146s +40d11m28.2199s',
 u'08h00m49.8934s +35d42m49.6331s',
 u'08h28m43.368s +45d45m17.2955s',
 u'08h37m13.5609s +36d30m37.3449s',
 u'08h37m57.9144s +38d37m27.1164s',
 u'08h41m58.4701s +39d21m20.9741s',
 u'08h53m58.3643s -00d11m08.0473s',
 u'09h10m46.4006s +04d14m58.5125s',
 u'09h13m38.304s -01d07m08.6819s',
 u'09h14m32.0166s +01d09m12.4277s',
 u'09h24m17.6496s +39d29m20.2547s',
 u'09h32m26.3442s +09d25m26.1095s',
 u'09h36m40.3458s -00d58m40.0921s',
 u'09h38m04.2177s +53d17m43.9106s',
 u'10h02m46.8558s +00d21m03.9938s',
 u'10h05m09.5996s +50d19m29.7953s',
 u'10h06m27.4687s +48d04m20.047s',
 u'10h09m41.3471s +25d01m04.0768s',
 u'10h10m01.5087s +40d37m55.4805s',
 u'10h26m18.8051s +46d14m45.2755s',
 u'10h38m57.371s +50d27m07.9806s'

In [4]:
QPQ7_fil = imp.find_module('enigma')[1] + '/data/qpq/qpq7_pairs.fits.gz'
QPQ7 = xxf.bintab_to_table(QPQ7_fil)

x.fits.bintab_to_table: Reading /Users/lwymarie/python/enigma/enigma/data/qpq/qpq7_pairs.fits.gz


In [33]:
for cc in radec_liam:
    if len(np.where(cc.separation(radec_qpq9) < 5*u.arcsec)[0]) > 0:
        print(cc)

<SkyCoord (ICRS): (ra, dec) in deg
    (62.47579167, -4.19361389)>
<SkyCoord (ICRS): (ra, dec) in deg
    (192.45075, 6.12055556)>
<SkyCoord (ICRS): (ra, dec) in deg
    (130.4969125, 39.3611)>
<SkyCoord (ICRS): (ra, dec) in deg
    (210.539675, 47.02161944)>
<SkyCoord (ICRS): (ra, dec) in deg
    (330.70127917, 12.61563333)>
<SkyCoord (ICRS): (ra, dec) in deg
    (120.20308333, 35.70869444)>
<SkyCoord (ICRS): (ra, dec) in deg
    (137.69455417, 4.24676389)>
<SkyCoord (ICRS): (ra, dec) in deg
    (215.22883333, 16.06192222)>
<SkyCoord (ICRS): (ra, dec) in deg
    (159.75005417, 50.44801111)>
<SkyCoord (ICRS): (ra, dec) in deg
    (196.51479167, 61.97644444)>
<SkyCoord (ICRS): (ra, dec) in deg
    (156.5671625, 46.23911944)>
<SkyCoord (ICRS): (ra, dec) in deg
    (246.90795833, 22.25258611)>
<SkyCoord (ICRS): (ra, dec) in deg
    (175.43927917, 7.40646389)>
<SkyCoord (ICRS): (ra, dec) in deg
    (138.41238333, -1.11795)>
<SkyCoord (ICRS): (ra, dec) in deg
    (133.48954167, -0.18502778)

<SkyCoord (ICRS): (ra, dec) in deg
    (244.524375, 9.33447222)>

In [69]:
from astropy.cosmology import FlatLambdaCDM
cosmo = FlatLambdaCDM(H0=70, Om0=0.26)
c_QPQ7 = SkyCoord(QPQ7['RAD']*u.deg,QPQ7['DECD']*u.deg,frame='icrs')
c_QPQ7_bg = SkyCoord(ra=QPQ7['RAD_BG']*u.deg,dec=QPQ7['DECD_BG']*u.deg)
kpc_amin = cosmo.kpc_proper_per_arcmin(QPQ7['Z_FG'])
ang_sep = c_QPQ7.separation(c_QPQ7_bg).to('arcmin')
                                          
for qq,cc in enumerate(c_QPQ7):
    if kpc_amin[qq]*ang_sep[qq] < 300*u.kpc:
        if len(np.where(cc.separation(c_liam) < 5*u.arcsec)[0]) > 0: # in QPQ7
            if len(np.where(cc.separation(radec_qpq9) < 5*u.arcsec)[0]) == 0: # not in QPQ9
                print(cc.to_string('hmsdms'),c_QPQ7_bg[qq].to_string('hmsdms'))
                print(kpc_amin[qq]*ang_sep[qq])
                print(QPQ7['Z_FG','Z_BG'][qq])

(u'12h31m43.0985s +00d28m46.2929s', u'12h31m41.7338s +00d29m13.9428s')
270.595353028 kpc
     Z_FG          Z_BG    
------------- -------------
3.21249008179 3.30788516998


In [67]:
good_coord = SkyCoord('12h31m43.0985s','+00d28m46.2929s',frame='icrs')
for qq,cc in enumerate(c_liam):
    if cc.separation(good_coord) < 5*u.arcsec:
        print(liam['REDSHIFT','RAJ2000','DEJ2000'][qq])

REDSHIFT    RAJ2000       DEJ2000   
-------- ------------- -------------
  3.2141 12h31m43.090s +00d28m46.20s


In [71]:
from specdb.specdb import IgmSpec
igmsp = IgmSpec()
ID_fg, ID_bg = igmsp.pairs(0.69*u.arcmin, 3000.*u.km/u.s)
c_igmsp = SkyCoord(igmsp.cat['RA'][ID_fg]*u.deg,igmsp.cat['DEC'][ID_fg]*u.deg,frame='icrs')
c_igmsp_bg = SkyCoord(igmsp.cat['RA'][ID_bg]*u.deg,igmsp.cat['DEC'][ID_bg]*u.deg,frame='icrs')
kpc_amin = cosmo.kpc_proper_per_arcmin(igmsp.cat['zem'][ID_fg])
ang_sep = c_igmsp.separation(c_igmsp_bg).to('arcmin')
for qq,cc in enumerate(c_igmsp):
    if kpc_amin[qq]*ang_sep[qq] < 300 *u.kpc:
        if len(np.where(cc.separation(c_liam) < 5*u.arcsec)[0]) > 0: # in igmspec 
            if len(np.where(cc.separation(c_liam) < 5*u.arcsec)[0]) > 1:
                print('check multiple quasars')
            if (len(np.where(cc.separation(c_QPQ7) < 5*u.arcsec)[0]) == 0) & \
            (len(np.where(cc.separation(c_QPQ9) < 5*u.arcsec)[0]) == 0): # not in QPQ7, QPQ9
                print(cc.to_string('hmsdms'),c_igmsp_bg[qq].to_string('hmsdms'))
                print(kpc_amin[qq]*ang_sep[qq])

Using /Users/lwymarie/Desktop/IGMspec_DB_v02.hdf5 for the catalog file
Using /Users/lwymarie/Desktop/IGMspec_DB_v02.hdf5 for the DB file
Available surveys: [u'BOSS_DR12', u'HSTQSO', u'SDSS_DR7', u'KODIAQ_DR1', u'HD-LLS_DR1', u'2QZ', u'ESI_DLA', u'HDLA100', u'GGG', u'COS-Halos', u'HST_z2', u'COS-Dwarfs', u'XQ-100']
Database is igmspec
Created on 2016-Oct-10
check multiple quasars
(u'02h39m46.4276s -01d06m40.4939s', u'02h39m46.4454s -01d06m44.1288s')
31.0655330711 kpc
(u'14h33m45.501s +06d41m09.9867s', u'14h33m44.5509s +06d41m11.9347s')
121.960789857 kpc
(u'23h38m45.1943s -00d03m27.1218s', u'23h38m45.451s -00d03m31.8384s')
51.3253173159 kpc
(u'02h01m43.4873s +00d32m22.713s', u'02h01m42.2498s +00d32m18.4626s')
0.0 kpc
check multiple quasars


In [21]:
from astropy.table import Table
myers = Table(igmsp.idb.hdf['quasars'].value)
c_myers = SkyCoord(myers['RA']*u.deg,myers['DEC']*u.deg,frame='icrs')
c_myers[0]

<SkyCoord (ICRS): (ra, dec) in deg
    (0.027228, 0.51534098)>

In [68]:
for qq,cc in enumerate(c_igmsp):
    if kpc_amin[qq]*ang_sep[qq] < 300 *u.kpc:
        if len(np.where(cc.separation(c_liam) < 5*u.arcsec)[0]) == 0: # not in liam  
            if len(np.where(cc.separation(c_QPQ7) < 5*u.arcsec)[0]) == 0: # not in QPQ7
                if len(np.where(cc.separation(c_myers) < 5*u.arcsec)[0]) > 0: # in Myers
                    if myers['ZEM_SOURCE'][np.where(cc.separation(c_myers) < 5*u.arcsec)[0][0]] == 'SDSS-HW': # good z
                        if ((myers['ZEM'][np.where(cc.separation(c_myers) < 5*u.arcsec)[0][0]] > 1.6) & \
                        (myers['ZEM'][np.where(cc.separation(c_myers) < 5*u.arcsec)[0][0]] < 2.1)): # QPQ z
                            print(c_myers[np.where(cc.separation(c_myers) < 5*u.arcsec)[0][0]].to_string('hmsdms'))

02h25m26.3251s -01d14m34.3572s
02h32m26.5384s -00d11m45.096s
02h46m03.6823s -00d32m11.7492s
09h21m22.8918s +56d31m27.6022s
10h28m21.2549s +24d01m21.7932s
12h16m57.8174s +15d27m06.5808s
13h53m06.3464s +11d38m04.7134s
14h03m55.1514s +37d34m01.7404s
14h36m09.1443s +31d34m26.7549s
14h56m19.3323s +11d37m34.2366s
15h43m49.1162s +44d45m14.7354s
15h57m33.9807s +29d28m44.3385s
16h54m42.2095s +25d12m49.2284s
00h40m18.2178s +00d55m30.9324s
00h01m25.1443s +00d00m09.4356s
00h08m04.2269s -00d39m22.9824s
00h08m05.1814s -00d39m46.7819s
00h42m38.2384s +13d50m54.8069s
00h47m57.2575s +14d47m41.9591s
01h03m23.8408s -00d02m54.204s
01h06m16.3966s +00d56m56.85s
01h54m48.9377s +00d20m42.774s
02h06m00.4834s +22d38m40.4979s
02h14m16.9583s -00d52m29.1468s
02h24m47.8958s -00d47m00.3552s
02h42m57.2067s -00d45m49.5071s
02h50m38.692s -00d47m39.1056s
03h34m44.0341s -00d58m26.1984s
07h49m54.1077s +37d02m16.7661s
08h09m45.1721s +45d39m18.1055s
08h12m23.1683s +26d20m00.9087s
08h14m27.2095s +04d02m29.1343s
08h18m00.4907s

In [65]:
c_1 = SkyCoord('02h25m17.6834s','+00d48m21.924s',frame='icrs')
c_2 = SkyCoord('02h25m17.6001s','+00d48m22s',frame='icrs')
c_1.separation(c_2)

<Angle 0.0003476904883323653 deg>

In [53]:
(specs, metas) = igmsp.spec_from_coord('020143.49+003222.7')
metas

Your search yielded 1 match[es]
Staged 0 spectra totalling 0 Gb
No spectra matching in survey 2QZ
Staged 1 spectra totalling 9.3e-05 Gb
Loaded spectra
Staged 0 spectra totalling 0 Gb
No spectra matching in survey COS-Dwarfs
Staged 0 spectra totalling 0 Gb
No spectra matching in survey COS-Halos
Staged 0 spectra totalling 0 Gb
No spectra matching in survey ESI_DLA
Staged 0 spectra totalling 0 Gb
No spectra matching in survey GGG
Staged 0 spectra totalling 0 Gb
No spectra matching in survey HD-LLS_DR1
Staged 0 spectra totalling 0 Gb
No spectra matching in survey HDLA100
Staged 0 spectra totalling 0 Gb
No spectra matching in survey HSTQSO
Staged 0 spectra totalling 0 Gb
No spectra matching in survey HST_z2
Staged 0 spectra totalling 0 Gb
No spectra matching in survey KODIAQ_DR1
Staged 1 spectra totalling 6.4e-05 Gb
Loaded spectra
Staged 0 spectra totalling 0 Gb
No spectra matching in survey XQ-100


[<Table length=1>
     SDSS_NAME            RA           DEC       ... INSTR GRATING TELESCOPE 
       str18           float64       float64     ...  str4   str4    str10   
 ------------------ ------------- -------------- ... ----- ------- ----------
 020143.48+003222.7 30.4311972623 0.539642504377 ...  BOSS    BOTH SDSS 2.5-M,
 <Table length=1>
       SDSSJ            RA      DEC    ... GRATING TELESCOPE  flag_zem
       str31         float64  float64  ...   str4    str10     str10  
 ------------------ --------- -------- ... ------- ---------- --------
 020143.48+003222.7 30.431195 0.539658 ...    BOTH SDSS 2.5-M  SDSS-HW]

In [36]:
metas[0]

<Table length=1>
    SDSS_NAME            RA           DEC       ... INSTR GRATING TELESCOPE 
      str18           float64       float64     ...  str4   str4    str10   
------------------ ------------- -------------- ... ----- ------- ----------
022517.67+004821.9 36.3236563298 0.806094386422 ...  BOSS    BOTH SDSS 2.5-M

In [37]:
metas[1]

<Table length=1>
      SDSSJ            RA      DEC   ... GRATING TELESCOPE  flag_zem
      str31         float64  float64 ...   str4    str10     str10  
------------------ --------- ------- ... ------- ---------- --------
022517.68+004821.9 36.323682 0.80609 ...    BOTH SDSS 2.5-M  SDSS-HW

In [59]:
c1 = SkyCoord('14h27m58.8897s','-01d21m30.3753s',frame='icrs')
np.where(c1.separation(c_QPQ9) < 5*u.arcsec)[0][0]

44

In [55]:
import warnings
warnings.warn("deprecated")

/Users/lwymarie/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: UserWarning: deprecated
  from ipykernel import kernelapp as app


In [62]:
qpqsp.cat[1816]

<Row index=1816>
sig_zem flag_zem flag_survey   zem      RA      DEC    IGM_ID STYPE PRIV_ID
float64   str9      int64    float64 float64  float64  int64   str3  int64 
------- -------- ----------- ------- -------- -------- ------ ----- -------
  0.000 BOSS_PCA           1   2.805  11.4822   0.1901  12537   QSO    1816

In [61]:
qpqsp.cat[4087]

<Row index=4087>
sig_zem flag_zem flag_survey   zem      RA      DEC    IGM_ID STYPE PRIV_ID
float64   str9      int64    float64 float64  float64  int64   str3  int64 
------- -------- ----------- ------- -------- -------- ------ ----- -------
  0.000 BOSS_PCA           1   2.805  11.4822   0.1901  12537   QSO    4087

In [95]:
100./299792. * (2800*(1+2.4))

3.175535037626087

In [200]:
sig = np.array([1,0,0,4,5])
msk = np.ones(5)
bad = np.where((sig <= 0.) | (sig is np.nan))
msk[bad] = 0
msk[np.array(bad)-2] = 0
msk[np.array(bad)+2] = 0
np.array(bad)-2

array([[-1,  0]])

In [199]:
twod_msk = np.ones((10,5))
twod_msk[1,np.array(bad)-2] = 0
bad[0]

array([1])

In [177]:
(bad == tuple()) is True

False

In [180]:
type(bad[0])

numpy.ndarray

In [201]:
for bb in bad:
    print(bb)

[1 2]


In [206]:
set([1,2,3,4,5,6]) - set([2,3,4])

{1, 5, 6}

In [226]:
def my_function(**kwargs):
    print str(kwargs)

my_function(a=12, b="abc")

{'a': 12, 'b': 'abc'}
