# Fiddling about with spectra

In [1]:
# imports
from specdb.specdb import SpecDB

## Load QPQ

In [2]:
qpq_fil = '/Users/lwymarie/Desktop/qpq_optical.hdf5'

In [5]:
qpqsp = SpecDB(db_file=qpq_fil)

Using /Users/lwymarie/Desktop/qpq_optical.hdf5 for the catalog file
Using /Users/lwymarie/Desktop/qpq_optical.hdf5 for the DB file
Available surveys: [u'GMOS', u'MODS', u'HIRES', u'MMT', u'XSHOOTER', u'MIKE', u'BOSS', u'MAGE', u'LRIS', u'SDSS', u'ESI']
Database is QPQ
Created on 2016-Oct-11


In [30]:
qpqsp.cat['RA'][12*36+4-1],qpqsp.cat['DEC'][12*36+4-1]

(180.12145833333332, 1.4961944444444446)

In [3]:
from astropy import units as u
from astropy.coordinates import SkyCoord
c = SkyCoord(ra=150.696425115*u.degree, dec=0.348057780352*u.degree, frame='icrs')
c.to_string('hmsdms')

u'10h02m47.142s +00d20m53.008s'

In [33]:
qpqsp.cat['PRIV_ID']

<Column name='PRIV_ID' dtype='int64' length=8454>
   0
   1
   2
   3
   4
   5
   6
   7
   8
   9
  10
  11
 ...
8442
8443
8444
8445
8446
8447
8448
8449
8450
8451
8452
8453

In [70]:
(specs, metas) = qpqsp.spec_from_coord('220248.31+123656.3',private=True)
import numpy as np
import matplotlib.pyplot as plt
metas[0]

Your search yielded 6 match[es]
Staged 6 spectra totalling 0.0006 Gb
Loaded spectra
Staged 0 spectra totalling 0 Gb
No spectra matching in survey ESI
Staged 0 spectra totalling 0 Gb
No spectra matching in survey GMOS
Staged 0 spectra totalling 0 Gb
No spectra matching in survey HIRES
Staged 1 spectra totalling 8.4e-05 Gb
Loaded spectra
Staged 0 spectra totalling 0 Gb
No spectra matching in survey MAGE
Staged 0 spectra totalling 0 Gb
No spectra matching in survey MIKE
Staged 0 spectra totalling 0 Gb
No spectra matching in survey MMT
Staged 0 spectra totalling 0 Gb
No spectra matching in survey MODS
Staged 0 spectra totalling 0 Gb
No spectra matching in survey SDSS
Staged 0 spectra totalling 0 Gb
No spectra matching in survey XSHOOTER


<Table length=6>
sig_zem flag_zem flag_survey   zem   ... TELESCOPE  GRATING SURVEY_ID VERSION
float64   str9      int64    float64 ...   str10      str4     str5     str7 
------- -------- ----------- ------- ... ---------- ------- --------- -------
    0.0      QPQ           1   2.508 ... SDSS 2.5-M    BOTH     DUMMY  v5_5_0
    0.0      QPQ           1   2.508 ... SDSS 2.5-M    BOTH     DUMMY  v5_5_0
    0.0      QPQ           1   2.508 ... SDSS 2.5-M    BOTH     DUMMY  v5_5_0
    0.0      QPQ           1   2.508 ... SDSS 2.5-M    BOTH     DUMMY  v5_7_0
    0.0      QPQ           1   2.508 ... SDSS 2.5-M    BOTH     DUMMY  v5_5_0
    0.0      QPQ           1   2.508 ... SDSS 2.5-M    BOTH     DUMMY  v5_7_0

In [71]:
specs[0].select = 2
specs[0].plot()

In [11]:
np.where(specs[0].co != 0)

(array([], dtype=int64),)

In [ ]:
%matplotlib inline
spec[-1].normalize(spec[-1].co)
spec[-1].normalized_spec().plot()

In [139]:
spec[0].data['wave'][0].data[0]

3993.5324129177138

In [144]:
for ii,cc in enumerate(conti):
    if (conti[ii] != conti[ii+1]):
        print(ii+1)
        break


711


In [146]:
meta[0]['SPEC_FILE']

<Column name='SPEC_FILE' dtype='str78' length=1>
/u/xavier/Dropbox//QSOPairs/data/ESI_redux/./SDSSJ022519.50+004823.7_F.fits.gz

In [19]:
igmsp = SpecDB(db_file='/Users/lwymarie/Desktop/IGMspec_DB_v01.hdf5')
spec2, meta2 = igmsp.spec_from_coord('013816.37-004145.3')

Using /Users/lwymarie/Desktop/IGMspec_DB_v01.hdf5 for the catalog file
Using /Users/lwymarie/Desktop/IGMspec_DB_v01.hdf5 for the DB file
Available surveys: [u'BOSS_DR12', u'SDSS_DR7', u'KODIAQ_DR1', u'HD-LLS_DR1', u'2QZ', u'ESI_DLA', u'HDLA100', u'GGG', u'COS-Halos', u'HST_z2', u'XQ-100']
Your search yielded 0 match[es]


/Users/lwymarie/python/specdb/specdb/specdb.py:78: UserWarning: No sources found at your coordinate.  Returning none
  warnings.warn("No sources found at your coordinate.  Returning none")


In [13]:
meta2[0]['SDSS_NAME'],meta2[0]['SDSS_DR7'],meta2[0]['NSPEC_BOSS'],meta2[0]['INSTR'],meta2[0]['SPEC_FILE']

(<Column name='SDSS_NAME' dtype='str18' length=1>
 100247.14+002052.9, <Column name='SDSS_DR7' dtype='int32' length=1>
 0, <Column name='NSPEC_BOSS' dtype='int32' length=1>
 0, <Column name='INSTR' dtype='str4' length=1>
 BOSS, <Column name='SPEC_FILE' dtype='str28' length=1>
 spec-3829-55300-0682.fits.gz)

In [11]:
from astropy import units as u
spec3, meta3 = qpqsp.spec_from_coord('100247.142+002053.0',private=True)

Your search yielded 0 match[es]


/Users/lwymarie/python/specdb/specdb/specdb.py:78: UserWarning: No sources found at your coordinate.  Returning none
  warnings.warn("No sources found at your coordinate.  Returning none")


In [12]:
spec3[2]

TypeError: 'NoneType' object has no attribute '__getitem__'

In [ ]:
spec3[2].plot()

In [ ]:
spec3[2].sig

In [ ]:
import numpy as np
len(spec3[2].flux)

In [ ]:
meta3[2]

In [ ]:
len(spec3[0:-1][0].flux)

In [ ]:
spec3[0].flux

In [ ]:
spec3[0].sig

In [14]:
spec_file = '/Marie_X/QPQ9/Continuua/XSHOOTER/SDSSJ091338.97-010704.6_F_c.fits'

In [ ]:
'J0913' in spec_file and 'XSHOOTER' in spec_file

In [25]:
spec4, meta4 = igmsp.spec_from_coord('074853.65+222525.2')

Your search yielded 0 match[es]


In [ ]:
meta3[['INSTR']

In [ ]:
'XSHOOTER' in meta3[2]['INSTR'][0]

In [ ]:
type(meta3)

In [ ]:
for meta in meta3:
    print('XSHOOTER' in meta['INSTR'][0])

In [ ]:
spec3[0]

In [ ]:
str1 = 'MagE'

In [ ]:
dir(str1)

In [ ]:
str1.capitalize

In [ ]:
str1.upper()

In [29]:
import matplotlib.pyplot as plt
import numpy as np
plt.plot(np.array([1,2,3]),np.array([1,2,3]))
plt.ylim(-2,2)
plt.show()

In [27]:
mpl.plot?

In [89]:
alist = [1,2,3]

In [90]:
alist[-1],alist[-2],alist[-3]

(3, 2, 1)

In [15]:
import numpy as np
wave = np.outer(np.ones(3), np.arange(100))

In [16]:
wave

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
         22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
         33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
         44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
         55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
         66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
         77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
         88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
         99.],
       [  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
         22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
         33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
         44.,  45.,  46

[0]

In [55]:
nplt = 32 
pages = nplt//15 + ((nplt % 15) > 0)
for ipage in range(pages):
    print(ipage)
range(pages)[0:3]

0
1
2


[0, 1, 2]

In [50]:
outfil = 'plt_qpq9_zNIR_{:d}_page{:d}.pdf'.format(1,2+1)
outfil

'plt_qpq9_zNIR_1_page3.pdf'

In [16]:
np.log(2.7)

0.99325177301028345

In [17]:
np.sqrt(4)

2.0

In [20]:
tau = np.array([1,2,3])
tau**2

array([1, 4, 9])

In [21]:
help(np.sum)

Help on function sum in module numpy.core.fromnumeric:

sum(a, axis=None, dtype=None, out=None, keepdims=False)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In that case, if `a` is signe

In [24]:
cumtau = np.cumsum(np.array([1,2,3]))

In [26]:
np.where(cumtau > 1)

(array([1, 2]),)

In [22]:
wavelength = np.array([1,2,3,4,5])
np.where((wavelength > 1) & (wavelength < 5))

(array([1, 2, 3]),)